### PR TITLE
fix: clean scanner logs output

### LINKED ISSUE #230: all trivy scanner logs should be json
**What steps did you take and what happened:**

Seeing non-json log lines, such as:
```
2022-06-08T01:58:32.588Z        INFO    Detected OS: debian
2022-06-08T01:58:32.588Z        INFO    Detecting Debian vulnerabilities...
2022-06-08T01:58:32.588Z        INFO    Number of language-specific files: 1
2022-06-08T01:58:32.588Z        INFO    Detecting gobinary vulnerabilities...
```

We should convert these to json if we can

### PR DESCRIPTION
**Pull request by ashnamehrotra**
**What this PR does / why we need it**:
Removes extra output logs produced by trivy library when scanning.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #230 

**Special notes for your reviewer**:
pr on top of #339

### CODE REVIEW

File: pkg/scanners/trivy/trivy.go [hunk 1]
```diff
@@ -89,11 +90,17 @@ func main() {
...
 	ctx := context.Background()
 
+	var err error
+
 	if err := logger.Configure(); err != nil {
 		fmt.Fprintln(os.Stderr, "error setting up logger:", err)
 		os.Exit(generalErr)
 	}
 
+	if trivylogger.Logger, err = trivylogger.NewLogger(false, true); err != nil {
```
Comment (sozercan) [inline pkg/scanners/trivy/trivy.go]: looks like this disables trivy's logger, so we won't get those logs. instead of disabling it, can we replace `trivylogger.Log` with our own logger or create a new zap logger?

something like
```
logger, err := zap.NewProduction()
...
sugar := logger.Sugar()
trivylogger.Logger = sugar
```

**Review by sozercan — CHANGES_REQUESTED** [review]
see comment

File: pkg/scanners/trivy/trivy.go (hunk 1 above)
Comment (ashnamehrotra) [reply pkg/scanners/trivy/trivy.go]: (resolved)

File: pkg/scanners/trivy/trivy.go [hunk 2]
```diff
@@ -89,11 +91,26 @@ func main() {
...
+	logger, err := zap.NewProduction()
+	if err != nil {
+		fmt.Fprintln(os.Stderr, "error setting up trivy logger:", err)
+		os.Exit(generalErr)
+	}
+
+	sugar := logger.Sugar()
+	trivylogger.Logger = sugar
+
+	if trivylogger.Logger, err = trivylogger.NewLogger(false, true); err != nil {
```
Comment (sozercan) [inline pkg/scanners/trivy/trivy.go]: i don't think we need this, isn't it going to overwrite the logger?

File: pkg/scanners/trivy/trivy.go (hunk 1 above)
Comment (sozercan) [reply pkg/scanners/trivy/trivy.go]: yes, just the trivy logs and the scanner logs

File: pkg/scanners/trivy/trivy.go [hunk 3]
```diff
@@ -89,11 +91,26 @@ func main() {
...
 
-	if err := logger.Configure(); err != nil {
+	var err error
+
+	if err = logger.Configure(); err != nil {
 		fmt.Fprintln(os.Stderr, "error setting up logger:", err)
 		os.Exit(generalErr)
 	}
 
+	logger, err := zap.NewProduction()
```
Comment (sozercan) [inline pkg/scanners/trivy/trivy.go:102]: let's add a comment that we are adding this because trivy logs are not json and we are doing this for json output

**Review by sozercan — APPROVED** [review]
LGTM
