### PR TITLE
fix: metrics fixes

### LINKED ISSUE #509: eraser metrics not recorded when scanner is disabled
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When the scanner is disabled, the total images removed is not recorded

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version: v0.5.0
- Kubernetes version: (use `kubectl version`):

### PR DESCRIPTION
**Pull request by ashnamehrotra**
**What this PR does / why we need it**:
- Moves controller-runtime metrics to same endpoint as otel eraser metrics
- Fixes eraser container metrics to report before writing to named pipe (when scanner was disabled it would return before recording the metrics)

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #509, #502

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by pmengelbert** [comment]
Can we modify the `metrics_test_scanner` to check that eraser metrics are received? Put it on a timer and fail if the timer elapses. Verify that it fails without this PR, then restore the changes and verify that it passes

**Comment by ashnamehrotra** [comment]
> Can we modify the `metrics_test_scanner` to check that eraser metrics are received? Put it on a timer and fail if the timer elapses. Verify that it fails without this PR, then restore the changes and verify that it passes

The metrics_test_scanner doesn't disable the scanner, so it wouldn't fail without this PR. Do you think we should add an e2e test that checks eraser metrics when scanner is disabled?

**Comment by pmengelbert** [comment]
Whoops, I meant `metrics_test_eraser`, which does disable the scanner. Does having the `collector` disabled also affect this issue? That is, if both scanner and collector are disabled, does this problem still happen? If so, you can just modify `metrics_test_eraser`. If not, we'll need a new (but very similar) test

**Comment by ashnamehrotra** [comment]
> Whoops, I meant `metrics_test_eraser`, which does disable the scanner. Does having the `collector` disabled also affect this issue? That is, if both scanner and collector are disabled, does this problem still happen? If so, you can just modify `metrics_test_eraser`. If not, we'll need a new (but very similar) test

It doesn't happen when scanner and collector are both disabled. I added another test that checks with just scanner disabled.

File: main.go [hunk 1]
```diff
@@ -45,7 +45,7 @@ import (
 var (
 	scheme               = runtime.NewScheme()
 	setupLog             = ctrl.Log.WithName("setup")
-	metricsAddr          = flag.String("metrics-bind-address", ":8080", "The address the metric endpoint binds to.")
+	metricsAddr          = flag.String("metrics-bind-address", ":8889", "The address the metric endpoint binds to.")
```
Comment (pmengelbert) [inline main.go:48]: What does this change do?

File: test/e2e/tests/metrics_test_eraser/eraser_test.go [hunk 2]
```diff
@@ -23,7 +23,7 @@ func TestMetrics(t *testing.T) {
 	metrics := features.New("Images_removed_run_total metric should report 1").
 		Assess("Alpine image is removed", func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
 			// deploy imagelist config
-			if err := util.DeployEraserConfig(cfg.KubeconfigFile(), util.TestNamespace, "../../test-data", "imagelist_alpine.yaml"); err != nil {
+			if err := util.DeployEraserConfig(cfg.KubeconfigFile(), util.EraserNamespace, "../../test-data", "imagelist_alpine.yaml"); err != nil {
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_eraser/eraser_test.go]: Why these changes?

File: test/e2e/tests/metrics_test_scanner/eraser_test.go [hunk 3]
```diff
@@ -28,16 +28,27 @@ func TestMetrics(t *testing.T) {
...
+
+			if err := util.GetManagerLogs(ctx, cfg, t); err != nil {
+				t.Error("error getting manager logs", err)
+			}
+
+			return ctx
+		}).
 		Assess("Check images_removed_run_total metric", func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
-			if _, err := util.KubectlCurlPod(cfg.KubeconfigFile(), util.TestNamespace); err != nil {
+			if _, err := util.KubectlCurlPod(cfg.KubeconfigFile(), util.EraserNamespace); err != nil {
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_scanner/eraser_test.go]: ditto: why?

File: main.go (hunk 1 above)
Comment (ashnamehrotra) [reply main.go:48]: its for #502 since runtime metrics are not a part of otel, we can't remove it but we can have them displayed with the rest of the collected metrics at the same endpoint

File: test/e2e/tests/metrics_test_eraser/eraser_test.go (hunk 2 above)
Comment (ashnamehrotra) [reply test/e2e/tests/metrics_test_eraser/eraser_test.go]: wanted to get logs for the metrics tests, but the other e2e tests had been using util.EraserNamespace instead of TestNamespace and that is what was used to get the logs. I can put up a separate PR to fix that to consistently use TestNamespace instead!

Comment (pmengelbert) [reply test/e2e/tests/metrics_test_eraser/eraser_test.go]: I'll put up a PR for that and you can rebase this PR on top of that. Best to keep things orderly when possible. All the tests are using `util.TestNamespace` except for the `collector_pipeline` test because it's not deployed via helm.

Comment (pmengelbert) [reply test/e2e/tests/metrics_test_eraser/eraser_test.go]: In all the `eraser_test.go` files, we should be be using `cfg.Namespace()` for all namespace references. That way, we can't get ourselves into trouble with having conflicting namespaces, it's just set once in `main_test.go` and everything else refers to that.

Comment (ashnamehrotra) [reply test/e2e/tests/metrics_test_eraser/eraser_test.go]: They create the TestNamespace, but still use EraserNamespace when deploying Eraser. The get logs methods will need to be changed too to use TestNamespace instead or take namespace as an argument.

Comment (pmengelbert) [reply test/e2e/tests/metrics_test_eraser/eraser_test.go]: yeah, they need to take a namespace as an argument.

**Comment by pmengelbert** [comment]
We should hold off merging this until #530 is merged

File: test/e2e/tests/metrics_test_disable_scanner/main_test.go [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+	eraserImage := util.ParsedImages.EraserImage
+	managerImage := util.ParsedImages.ManagerImage
+	collectorImg := util.ParsedImages.CollectorImage
+
+	util.Testenv = env.NewWithConfig(envconf.New())
+	// Create KinD Cluster
+	util.Testenv.Setup(
+		envfuncs.CreateKindClusterWithConfig(util.KindClusterName, util.NodeVersion, "../../kind-config.yaml"),
+		envfuncs.CreateNamespace(util.EraserNamespace),
+		util.DeployOtelCollector(util.EraserNamespace),
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_disable_scanner/main_test.go]: You'll want to switch these to `util.TestNamespace`

File: test/e2e/tests/metrics_test_disable_scanner/main_test.go [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.ManagerImage),
+		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.CollectorImage),
+		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.Image),
+		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.VulnerableImage),
+		util.DeployEraserHelm(util.EraserNamespace,
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_disable_scanner/main_test.go]: `util.TestNamespace`

File: test/e2e/tests/metrics_test_eraser/eraser_test.go (hunk 2 above)
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_eraser/eraser_test.go]: use `cfg.Namespace()`

File: test/e2e/tests/metrics_test_eraser/eraser_test.go [hunk 6]
```diff
@@ -33,16 +33,27 @@ func TestMetrics(t *testing.T) {
...
+
+			if err := util.GetManagerLogs(ctx, cfg, t); err != nil {
+				t.Error("error getting manager logs", err)
+			}
+
+			return ctx
+		}).
 		Assess("Check images_removed_run_total metric", func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
-			if _, err := util.KubectlCurlPod(cfg.KubeconfigFile(), util.TestNamespace); err != nil {
+			if _, err := util.KubectlCurlPod(cfg.KubeconfigFile(), util.EraserNamespace); err != nil {
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_eraser/eraser_test.go]: `cfg.Namespace()`

File: test/e2e/tests/metrics_test_eraser/eraser_test.go [hunk 7]
```diff
@@ -33,16 +33,27 @@ func TestMetrics(t *testing.T) {
...
 				t.Error(err, "error running curl pod")
 			}
 
-			if _, err := util.KubectlWait(cfg.KubeconfigFile(), "temp", util.TestNamespace); err != nil {
+			if _, err := util.KubectlWait(cfg.KubeconfigFile(), "temp", util.EraserNamespace); err != nil {
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_eraser/eraser_test.go]: `cfg.Namespace()`

File: test/e2e/tests/metrics_test_eraser/eraser_test.go [hunk 8]
```diff
@@ -33,16 +33,27 @@ func TestMetrics(t *testing.T) {
...
 				t.Error(err, "error waiting for temp curl pod")
 			}
 
-			output, err := util.KubectlExecCurl(cfg.KubeconfigFile(), "temp", "http://otel-collector/metrics", util.TestNamespace)
+			output, err := util.KubectlExecCurl(cfg.KubeconfigFile(), "temp", "http://otel-collector/metrics", util.EraserNamespace)
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_eraser/eraser_test.go]: `cfg.Namespace()`

File: test/e2e/tests/metrics_test_eraser/main_test.go [hunk 9]
```diff
@@ -26,12 +26,12 @@ func TestMain(m *testing.M) {
 	// Create KinD Cluster
 	util.Testenv.Setup(
 		envfuncs.CreateKindClusterWithConfig(util.KindClusterName, util.NodeVersion, "../../kind-config.yaml"),
-		envfuncs.CreateNamespace(util.TestNamespace),
-		util.DeployOtelCollector(util.TestNamespace),
+		envfuncs.CreateNamespace(util.EraserNamespace),
+		util.DeployOtelCollector(util.EraserNamespace),
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_eraser/main_test.go]: `util.TestNamespace`

File: test/e2e/tests/metrics_test_eraser/main_test.go [hunk 10]
```diff
@@ -26,12 +26,12 @@ func TestMain(m *testing.M) {
...
 		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.ManagerImage),
 		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.Image),
 		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.VulnerableImage),
-		util.DeployEraserHelm(util.TestNamespace,
+		util.DeployEraserHelm(util.EraserNamespace,
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_eraser/main_test.go]: `util.TestNamespace`

File: test/e2e/tests/metrics_test_scanner/eraser_test.go (hunk 3 above)
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_scanner/eraser_test.go]: `cfg.Namespace()`

File: test/e2e/tests/metrics_test_scanner/eraser_test.go [hunk 11]
```diff
@@ -28,16 +28,27 @@ func TestMetrics(t *testing.T) {
...
 				t.Error(err, "error running curl pod")
 			}
 
-			if _, err := util.KubectlWait(cfg.KubeconfigFile(), "temp", util.TestNamespace); err != nil {
+			if _, err := util.KubectlWait(cfg.KubeconfigFile(), "temp", util.EraserNamespace); err != nil {
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_scanner/eraser_test.go]: `cfg.Namespace()`

File: test/e2e/tests/metrics_test_scanner/eraser_test.go [hunk 12]
```diff
@@ -28,16 +28,27 @@ func TestMetrics(t *testing.T) {
...
 				t.Error(err, "error waiting for temp curl pod")
 			}
 
-			output, err := util.KubectlExecCurl(cfg.KubeconfigFile(), "temp", "http://otel-collector/metrics", util.TestNamespace)
+			output, err := util.KubectlExecCurl(cfg.KubeconfigFile(), "temp", "http://otel-collector/metrics", util.EraserNamespace)
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_scanner/eraser_test.go]: `cfg.Namespace()`

File: test/e2e/tests/metrics_test_scanner/eraser_test.go [hunk 13]
```diff
@@ -58,7 +69,7 @@ func TestMetrics(t *testing.T) {
 			return ctx
 		}).
 		Assess("Check vulnerable_images_run_total metric", func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
-			output, err := util.KubectlExecCurl(cfg.KubeconfigFile(), "temp", "http://otel-collector/metrics", util.TestNamespace)
+			output, err := util.KubectlExecCurl(cfg.KubeconfigFile(), "temp", "http://otel-collector/metrics", util.EraserNamespace)
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_scanner/eraser_test.go]: `cfg.Namespace()`

File: test/e2e/tests/metrics_test_scanner/main_test.go [hunk 14]
```diff
@@ -28,14 +28,14 @@ func TestMain(m *testing.M) {
 	// Create KinD Cluster
 	util.Testenv.Setup(
 		envfuncs.CreateKindClusterWithConfig(util.KindClusterName, util.NodeVersion, "../../kind-config.yaml"),
-		envfuncs.CreateNamespace(util.TestNamespace),
-		util.DeployOtelCollector(util.TestNamespace),
+		envfuncs.CreateNamespace(util.EraserNamespace),
+		util.DeployOtelCollector(util.EraserNamespace),
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_scanner/main_test.go]: `util.TestNamespace`

File: test/e2e/tests/metrics_test_scanner/main_test.go [hunk 15]
```diff
@@ -28,14 +28,14 @@ func TestMain(m *testing.M) {
...
 		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.ManagerImage),
 		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.Image),
 		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.CollectorImage),
 		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.ScannerImage),
 		envfuncs.LoadDockerImageToCluster(util.KindClusterName, util.VulnerableImage),
-		util.DeployEraserHelm(util.TestNamespace,
+		util.DeployEraserHelm(util.EraserNamespace,
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_scanner/main_test.go]: `util.TestNamespace`

File: test/e2e/tests/metrics_test_disable_scanner/eraser_test.go [hunk 16]
```diff
@@ -0,0 +1,74 @@
...
+			}
+
+			if err := util.GetManagerLogs(ctx, cfg, t); err != nil {
+				t.Error("error getting manager logs", err)
+			}
+
+			return ctx
+		}).
+		Assess("Check images_removed_run_total metric", func(ctx context.Context, t *testing.T, cfg *envconf.Config) context.Context {
+			if _, err := util.KubectlCurlPod(cfg.KubeconfigFile(), util.EraserNamespace); err != nil {
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_disable_scanner/eraser_test.go]: Use `cfg.Namespace()`

File: test/e2e/tests/metrics_test_disable_scanner/eraser_test.go [hunk 17]
```diff
@@ -0,0 +1,74 @@
...
+				t.Error(err, "error running curl pod")
+			}
+
+			if _, err := util.KubectlWait(cfg.KubeconfigFile(), "temp", util.EraserNamespace); err != nil {
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_disable_scanner/eraser_test.go]: `cfg.Namespace()`

File: test/e2e/tests/metrics_test_disable_scanner/eraser_test.go [hunk 18]
```diff
@@ -0,0 +1,74 @@
...
+				t.Error(err, "error waiting for temp curl pod")
+			}
+
+			output, err := util.KubectlExecCurl(cfg.KubeconfigFile(), "temp", "http://otel-collector/metrics", util.EraserNamespace)
```
Comment (pmengelbert) [inline test/e2e/tests/metrics_test_disable_scanner/eraser_test.go]: `cfg.Namespace()`

**Review by pmengelbert — CHANGES_REQUESTED** [review]

**Review by pmengelbert — APPROVED** [review]
LGTM Thanks for your patience!
