### PR TITLE
Fix alias bug

### LINKED ISSUE #130: An image may not be deleted if it is an alias for another image
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```bash
$ docker pull docker.io/library/nginx:latest
$ docker tag docker.io/library/nginx:latest registry.test/nginx:one
$ docker tag docker.io/library/nginx:latest registry.test/nginx:two
$ docker push registry.test/nginx:one
$ docker push registry.test/nginx:two
$ cat <<'EOF' | kubectl apply -f -
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
    - image: registry.test/nginx:one
      name: nginxone
  nodeName: mynode1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
    - image: registry.test/nginx:two
      name: nginxtwo
  nodeName: mynode1
EOF

$ kubectl delete pod nginx1 nginx2
$ cat <<'EOF' | kubectl apply -f -
---
apiVersion: eraser.sh/v1alpha1
kind: ImageList
metadata:
  name: imagelist
spec:
  images:
    - registry.test/nginx:two
EOF

$ kubectl logs -n eraser-system eraser-mynode1 | jq
...
{
  "level": "info",
  "ts": 1649354133.998637,
  "logger": "eraser",
  "msg": "Image is not on node",
  "image": "registry.test/nginx:two"
}
...
```

**What did you expect to happen:**

In this case, registry.test/nginx:one and registry.test/nginx:two are aliases
for each other, and supplying the following to the imagelist_controller should
result in the underlying image being deleted:

```
spec:
  images:
    - registry.test/nginx:two
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

This is a result of the following code (`pkg/eraser/eraser.go:215`):

```go
	nonRunningNames := make(map[string]struct{}, len(allImages)-len(runningImages))
	for key := range nonRunningImages {
		if idMap[key] != nil && len(idMap[key]) > 0 {
			nonRunningNames[idMap[key][0]] = struct{}{}
		}
	}
```

Only the first image name is added to the set of images that aren't running. In
the program, `idMap[key]` looks like:

```json
  [
    "pengelbert.azurecr.io/nginx:one",
    "pengelbert.azurecr.io/nginx:two"
  ]
```

According to the above code, only `nginx:one` is added to the set of
non-running images. As a result, no match will be found between a) the provided
imagelist and b) the set of non-running images.

**Environment:**

- Eraser version: v0.1.0
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"56709e92afa973c26fad3d4a44723fefa51481b7", GitTreeState:"clean", BuildDate:"2022-03-10T07:59:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

### PR DESCRIPTION
**Pull request by pmengelbert**
**What this PR does / why we need it**:
* Fixes a bug whereby images supplied in the imagelist were not being removed. This would happen consistently when one image was referred to by multiple names.  For a more thorough description of the bug, see #130 .
* Streamlines the removal logic, so that we can always delete by digest. Even when a name is provided, it is first mapped to a digest, then removed by digest.
* Adds an e2e test to prevent regression.
* A solid effort at tidying and refactoring in `eraser.go`.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #130 

**Special notes for your reviewer**:

### CODE REVIEW

File: test/e2e/utils.go [hunk 1]
```diff
@@ -215,3 +233,24 @@ func checkImageRemoved(ctx context.Context, t *testing.T, nodes []string, images
 		t.Error("not all nodes cleaned")
 	}
 }
+
+func dockerPullImage(image string) (string, error) {
+	args := []string{"pull", image}
+	cmd := exec.Command("docker", args...)
+	stdoutStderr, err := cmd.CombinedOutput()
+	return strings.TrimSpace(string(stdoutStderr)), err
```
Comment (cpuguy83) [inline test/e2e/utils.go]: Can you inject `stdoutStderr` into these error messages

e.g. 

```suggestion
	if err != nil {
		err = fmt.Errorf("%w: %s", err, stdoutStderr)
	}
	return strings.TrimSpace(string(stdoutStderr)), err
```

Otherwise we just end up with something like `fork/exec: exit status 1` as the error message.

**Review by cpuguy83 — CHANGES_REQUESTED** [review]

File: test/e2e/utils.go (hunk 1 above)
Comment (pmengelbert) [reply test/e2e/utils.go]: Changes made here and everywhere else I could find the pattern

**Review by cpuguy83 — APPROVED** [review]
LGTM

@ashnamehrotra Can you give this one a look?

**Review by ashnamehrotra — APPROVED** [review]
