### PR TITLE
fix: update owner references

### LINKED ISSUE #634: Deleting the eraser deployment should delete collector + eraser pods
**What steps did you take and what happened:**
```
# collector is in status “completed”
> kgpa
NAMESPACE       NAME                                                READY   STATUS      RESTARTS   AGE
eraser-system   collector-aks-nodepool1-91382860-vmss000000-dzdq6   0/3     Completed   0          6m37s
eraser-system   eraser-controller-manager-5947db8bdc-j8x6l          1/1     Running     0          6m39s
kube-system     azure-ip-masq-agent-kdz5n                           1/1     Running     0          40h
kube-system     cloud-node-manager-vq9b4                            1/1     Running     0          40h
kube-system     coredns-59b6bf8b4f-2hhsn                            1/1     Running     0          40h
kube-system     coredns-59b6bf8b4f-j4rn6                            1/1     Running     0          40h
kube-system     coredns-autoscaler-5655d66f64-t7wnf                 1/1     Running     0          40h
kube-system     csi-azuredisk-node-79l8p                            3/3     Running     0          40h
kube-system     csi-azurefile-node-sdfnq                            3/3     Running     0          40h
kube-system     konnectivity-agent-6b7fd746c6-ghnn8                 1/1     Running     0          40h
kube-system     konnectivity-agent-6b7fd746c6-hfc69                 1/1     Running     0          40h
kube-system     kube-proxy-g5gmf                                    1/1     Running     0          40h
kube-system     metrics-server-7dd74d8758-mj2wc                     2/2     Running     0          40h
kube-system     metrics-server-7dd74d8758-qv5tc                     2/2     Running     0          40h

# delete deployment
> kdel deployment -n eraser-system eraser-controller-manager
deployment.apps "eraser-controller-manager" deleted

# collector pod exist over 3 hours
> kgpa
NAMESPACE       NAME                                                READY   STATUS      RESTARTS   AGE
eraser-system   collector-aks-nodepool1-91382860-vmss000000-dzdq6   0/3     Completed   0          170m
kube-system     azure-ip-masq-agent-kdz5n                           1/1     Running     0          43h
kube-system     cloud-node-manager-vq9b4                            1/1     Running     0          43h
kube-system     coredns-59b6bf8b4f-2hhsn                            1/1     Running     0          43h
kube-system     coredns-59b6bf8b4f-j4rn6                            1/1     Running     0          43h
kube-system     coredns-autoscaler-5655d66f64-t7wnf                 1/1     Running     0          43h
kube-system     csi-azuredisk-node-fcf9j                            3/3     Running     0          101m
kube-system     csi-azurefile-node-sdfnq                            3/3     Running     0          43h
kube-system     konnectivity-agent-6b7fd746c6-ghnn8                 1/1     Running     0          43h
kube-system     konnectivity-agent-6b7fd746c6-hfc69                 1/1     Running     0          43h
kube-system     kube-proxy-g5gmf                                    1/1     Running     0          43h
kube-system     metrics-server-7dd74d8758-mj2wc                     2/2     Running     0          43h
kube-system     metrics-server-7dd74d8758-qv5tc                     2/2     Running     0          43h

# delayOnSuccess was set as 10min
> rg cleanup: eraser.yaml -C 2
445-      imageJob:
446-        successRatio: 1.0
447:        cleanup:
448-          delayOnSuccess: 10m
449-          delayOnFailure: 24h
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

### PR DESCRIPTION
**Pull request by ashnamehrotra**
**What this PR does / why we need it**:
Fixes owner references to clean up all pods when deleting Eraser deployment. Eraser pods' owner references are now set to the jobtemplate, and the jobtemplate's owner references are set to the controller manager pod.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #634

**Special notes for your reviewer**:
Since ImageJob is not an object it does not have ObjectMeta field to set an owner reference.

### CODE REVIEW

File: controllers/imagecollector/imagecollector_controller.go [hunk 1]
```diff
@@ -253,6 +255,24 @@ func (r *Reconciler) handleJobDeletion(ctx context.Context, job *eraserv1.ImageJ
...
+			Name:      job.GetName(),
+		},
+		&template,
+	)
+	if err != nil {
+		return ctrl.Result{}, err
+	}
+	log.Info("Deleting pod template", "template", template.Name)
+	err = r.Delete(ctx, &template)
+	if err != nil {
```
Comment (pmengelbert) [inline controllers/imagecollector/imagecollector_controller.go]: nit:
```suggestion
	if err := r.Delete(ctx, &template); err != nil {
```

File: controllers/imagecollector/imagecollector_controller.go [hunk 2]
```diff
@@ -253,6 +255,24 @@ func (r *Reconciler) handleJobDeletion(ctx context.Context, job *eraserv1.ImageJ
...
+
+	template := corev1.PodTemplate{}
+	err = r.Get(ctx,
+		types.NamespacedName{
+			Namespace: eraserUtils.GetNamespace(),
+			Name:      job.GetName(),
+		},
+		&template,
+	)
+	if err != nil {
```
Comment (pmengelbert) [inline controllers/imagecollector/imagecollector_controller.go]:
```suggestion
	if err := r.Get(ctx,
		types.NamespacedName{
			Namespace: eraserUtils.GetNamespace(),
			Name:      job.GetName(),
		},
		&template,
	); err != nil {
```

File: controllers/imagecollector/imagecollector_controller.go [hunk 3]
```diff
@@ -449,17 +469,29 @@ func (r *Reconciler) createImageJob(ctx context.Context) (ctrl.Result, error) {
 		return reconcile.Result{}, err
 	}
 
+	// get manager pod with label control-plane=controller-manager
+	podList := corev1.PodList{}
+	err = r.List(ctx, &podList, client.InNamespace(utils.GetNamespace()), client.MatchingLabels{"control-plane": "controller-manager"})
+	if err != nil {
```
Comment (pmengelbert) [inline controllers/imagecollector/imagecollector_controller.go]: nit:
```suggestion
	if err := r.List(ctx, &podList, client.InNamespace(utils.GetNamespace()), client.MatchingLabels{"control-plane": "controller-manager"}); err != nil {
```

File: controllers/imagelist/imagelist_controller.go [hunk 4]
```diff
@@ -233,6 +234,24 @@ func (r *Reconciler) handleJobDeletion(ctx context.Context, job *eraserv1.ImageJ
...
 
+	template := corev1.PodTemplate{}
+	err = r.Get(ctx,
+		types.NamespacedName{
+			Namespace: eraserUtils.GetNamespace(),
+			Name:      job.GetName(),
+		},
+		&template,
+	)
+	if err != nil {
```
Comment (pmengelbert) [inline controllers/imagelist/imagelist_controller.go]: same as above

File: controllers/imagelist/imagelist_controller.go [hunk 5]
```diff
@@ -233,6 +234,24 @@ func (r *Reconciler) handleJobDeletion(ctx context.Context, job *eraserv1.ImageJ
...
+		return ctrl.Result{}, err
+	}
+
+	log.Info("Deleting pod template", "template", template.Name)
+	err = r.Delete(ctx, &template)
+	if err != nil {
```
Comment (pmengelbert) [inline controllers/imagelist/imagelist_controller.go]: same as above

File: controllers/imagelist/imagelist_controller.go [hunk 6]
```diff
@@ -364,12 +383,23 @@ func (r *Reconciler) handleImageListEvent(ctx context.Context, imageList *eraser
 		return reconcile.Result{}, err
 	}
 
+	// get manager pod with label control-plane=controller-manager
+	podList := corev1.PodList{}
+	err = r.List(ctx, &podList, client.InNamespace(utils.GetNamespace()), client.MatchingLabels{"control-plane": "controller-manager"})
+	if err != nil {
```
Comment (pmengelbert) [inline controllers/imagelist/imagelist_controller.go]: same as above

**Review by pmengelbert — CHANGES_REQUESTED** [review]
A few nits, but overall LGTM. I'd like to see an e2e test proving this out. Tests prevent regression and double as documentation.

**Review by pmengelbert — APPROVED** [review]
LGTM, great job!
