### PR TITLE
fix: label child imagejobs by owner

### LINKED ISSUE #455: imagelist generates multiple eraser pods one after another
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

create kind cluster with 1.25
create an image list (for example: `test/e2e/test-data/eraser_v1alpha1_imagelist_updated.yaml`)
eraser pod will spin up and then complete
another eraser pod will spin up and complete
...

```
eraser-system        eraser-eraser2-control-plane-vl722              0/1     Completed           0          13s
eraser-system        eraser-eraser2-control-plane-vl722              0/1     Completed           0          15s
eraser-system        eraser-eraser2-control-plane-vl722              0/1     Terminating         0          15s
eraser-system        eraser-eraser2-control-plane-vl722              0/1     Terminating         0          15s
eraser-system        eraser-eraser2-control-plane-ltctw              0/1     Pending             0          0s
eraser-system        eraser-eraser2-control-plane-ltctw              0/1     ContainerCreating   0          0s
eraser-system        eraser-eraser2-control-plane-ltctw              1/1     Running             0          10s
eraser-system        eraser-eraser2-control-plane-ltctw              0/1     Completed           0          13s
eraser-system        eraser-eraser2-control-plane-ltctw              0/1     Completed           0          15s
eraser-system        eraser-eraser2-control-plane-ltctw              0/1     Terminating         0          15s
eraser-system        eraser-eraser2-control-plane-ltctw              0/1     Terminating         0          15s
eraser-system        eraser-eraser2-control-plane-xmrfs              0/1     Pending             0          0s
eraser-system        eraser-eraser2-control-plane-xmrfs              0/1     ContainerCreating   0          0s
eraser-system        eraser-eraser2-control-plane-xmrfs              1/1     Running             0          10s
eraser-system        eraser-eraser2-control-plane-xmrfs              0/1     Completed           0          13s
eraser-system        eraser-eraser2-control-plane-xmrfs              0/1     Completed           0          15s
eraser-system        eraser-eraser2-control-plane-xmrfs              0/1     Terminating         0          15s
eraser-system        eraser-eraser2-control-plane-xmrfs              0/1     Terminating         0          15s
eraser-system        eraser-eraser2-control-plane-lrzhb              0/1     Pending             0          0s
eraser-system        eraser-eraser2-control-plane-lrzhb              0/1     ContainerCreating   0          0s
```

**What did you expect to happen:**

only single eraser pod will spin up

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Eraser version:
- Kubernetes version: (use `kubectl version`):

### PR DESCRIPTION
**Pull request by pmengelbert**
**What this PR does / why we need it**:

Prior to PR #339, the ImageCollector controller was able to filter out ImageJob events related to ImageJobs created by the ImageList controller. Because the ImageCollector CR was removed, we could no longer keep the `&handler.EnqueueRequestForOwner` condition below:

```
-               &handler.EnqueueRequestForOwner{OwnerType: &eraserv1alpha1.ImageCollector{}, IsController: true}, predicate.Funcs{
+               &handler.EnqueueRequestForObject{}, predicate.Funcs{
```

The removed line can't be restored because `eraserv1alpha1.ImageCollector` was removed as a type in PR #339. Therefore, we need to manually manage ownership of these imagejobs. To accomplish this, we use an imagejob's metadata to label it. We label it by the owning controller, and then check the label as a precondition for reconciling on an ImageJob event.

Update: the `imagelist_rm_images` test has been updated to catch the respawning imagejob. The updated test is very effective at detecting the error condition. It's been tested dozens of times to ensure that it will correctly fail under the right circumstances.

Signed-off-by: Peter Engelbert <pmengelbert@gmail.com>

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #455 

**Special notes for your reviewer**:
Opening this as a draft until there's been further discussion and testing.

### CODE REVIEW

File: test/e2e/tests/imagelist_rm_images/eraser_test.go [hunk 1]
```diff
@@ -28,9 +34,25 @@ func TestImageListTriggersEraserImageJob(t *testing.T) {
...
 				t.Error("Failed to clean eraser obejcts ", err)
 			}
+
+			// wait for collector deployment to be removed, to prevent conflicts or races
+			err = wait.For(util.NumPodsPresentForLabel(ctx, client, 0, collectorLabel), wait.WithTimeout(time.Minute*2), wait.WithInterval(time.Millisecond*500))
+			if err != nil {
+				t.Fatal(err)
+			}
+
+			//if err := wait.For(conditions.New(client.Resources().DeploymentConditionMatch()))
```
Comment (sozercan) [inline test/e2e/tests/imagelist_rm_images/eraser_test.go]: leftover?

Comment (pmengelbert) [reply test/e2e/tests/imagelist_rm_images/eraser_test.go]: fixed now

**Review by sozercan — APPROVED** [review]
Great work! LGTM
