### PR TITLE
fix: unset cpu limits

### LINKED ISSUE #434: unset cpu limits
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run

https://home.robusta.dev/blog/stop-using-cpu-limits/

### PR DESCRIPTION
**Pull request by ashnamehrotra**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #434 

**Special notes for your reviewer**:

### CODE REVIEW

File: test/e2e/util/utils.go [hunk 1]
```diff
@@ -764,25 +763,21 @@ func DeployEraserManifest(namespace, fileName string) env.Func {
...
-		if err != nil {
-			return ctx, err
-		}
-
 		// create excluded configmap and add docker.io/library/alpine
 		excluded := corev1.ConfigMap{
 			ObjectMeta: metav1.ObjectMeta{
 				GenerateName: "excluded",
 				Namespace:    EraserNamespace,
+				Labels:       map[string]string{"eraser.sh/exclude.list": "true"},
```
Comment (sozercan) [inline test/e2e/util/utils.go]: how was this working before?

Comment (ashnamehrotra) [reply test/e2e/util/utils.go]: the test wasn't waiting for the collector pods to finish, so when it checked that the images were still on the node it would return true right away

**Review by sozercan — APPROVED** [review]
LGTM, let's merge #486 first and we can rebase
