### PR TITLE
fix: consistently use test namespace for all e2e tests

### LINKED ISSUE #529: fix hardcoded namespace for configmap
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
["eraser-system" namespace is hardcoded for configmap](https://github.com/Azure/eraser/blob/cdab164c574925c75a3a8fadda71cb1c958cb7c6/controllers/imagecollector/imagecollector_controller.go#L347).

**What did you expect to happen:**
AKS and potentially others do not use the eraser-system namespace, so it shouldn't be hard-coded here.

### PR DESCRIPTION
**Pull request by pmengelbert**
The one exception is the `collector_pipeline` test, which is deployed using the manifest. Absent a way to generate a manifest with an alternative namespace, it's easier to just use the `eraser-system` namespace when deploying from manifest.

Signed-off-by: Peter Engelbert <pmengelbert@gmail.com>

**What this PR does / why we need it**:
Additionally fixes #529 by removing hardcoded reference to the `eraser-system` namespace.

**Which issue(s) this PR fixes** *(optional, using `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when the PR gets merged)*:
Fixes #529 

This should be merged before #510

### CODE REVIEW

File: test/e2e/tests/collector_pipeline/main_test.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ func TestMain(m *testing.M) {
 	// Create KinD Cluster
 	util.Testenv.Setup(
 		envfuncs.CreateKindClusterWithConfig(util.KindClusterName, util.NodeVersion, "../../kind-config.yaml"),
-		envfuncs.CreateNamespace(util.TestNamespace),
+		envfuncs.CreateNamespace(util.EraserNamespace),
```
Comment (ashnamehrotra) [inline test/e2e/tests/collector_pipeline/main_test.go:26]: we don't need to create the namespace before any of the tests besides metrics and exclusion list, so we should be able to get rid of this in the rest of the tests

**Review by ashnamehrotra — CHANGES_REQUESTED** [review]

File: test/e2e/tests/collector_pipeline/main_test.go (hunk 1 above)
Comment (ashnamehrotra) [inline test/e2e/tests/collector_pipeline/main_test.go:26]: we don't need to create the namespace before in the tests besides for metrics and exclusion list so we should be able to delete this in the rest

Comment (pmengelbert) [reply test/e2e/tests/collector_pipeline/main_test.go:26]: This is required now, because it sets `cfg.Namespace()` in the body of the e2e tests, so we need to create one namespace per e2e test

**Review by ashnamehrotra — APPROVED** [review]
LGTM
